#!/bin/bash
#PBS -N para-VDP
#PBS -l nodes=1:ppn=2
#PBS -m e
#PBS -o VDP/T_${T}-N_${N}-eps_${EPS}/log.o
#PBS -e VDP/T_${T}-N_${N}-eps_${EPS}/log.e

cd $PBS_O_WORKDIR

# Make that OpenMP uses a number ppn of threads
OMP_NUM_THREADS=$PBS_NUM_PPN
export  OMP_NUM_THREADS

# Folder management
rm -rf VDP/T_${T}-N_${N}-eps_${EPS}
mkdir VDP/T_${T}-N_${N}-eps_${EPS}

# Run
pyenv shell 3.6.2
python3 run_parareal.py -ode VDP -T ${T} -N ${N} -eps ${EPS}