#!/bin/bash
#PBS -N parareal
#PBS -l nodes=1:ppn=2
#PBS -m e
#PBS -o Brusselator/T_${T}-N_${N}-eps_${EPS}/log.o
#PBS -e Brusselator/T_${T}-N_${N}-eps_${EPS}/log.e

cd $PBS_O_WORKDIR

# Make that OpenMP uses a number ppn of threads
OMP_NUM_THREADS=$PBS_NUM_PPN
export  OMP_NUM_THREADS

# Folder management
rm -rf Brusselator/T_${T}-N_${N}-eps_${EPS}
mkdir Brusselator/T_${T}-N_${N}-eps_${EPS}

# Run
pyenv shell 3.6.2
python3 run_parareal.py -ode Brusselator -T ${T} -N ${N} -eps ${EPS}